FROM python:3-alpine
RUN apk add --no-cache libffi-dev
RUN apk add --no-cache gcc
RUN apk add --no-cache musl-dev
RUN pip3 install --no-cache-dir pip --upgrade
RUN pip3 install --no-cache-dir selenium
