name: build docker image

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  #  branches-ignore: [main]
    paths-ignore:
      - README.md
      - .github/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: dockerfile
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.image != '' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - python:3.7-alpine
          - python:3.8-alpine
          - python:3.9-alpine
          - python:3.10-alpine
          - python:3.11-alpine
          - python:3.7-slim
          - python:3.8-slim
          - python:3.9-slim
          - python:3.10-slim
          - python:3.11-slim
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip3 install -r requirements.txt
      - name: Build modify FROM to ${{ matrix.image }}
        run: python3 dockerfile_generator.py validate ${{ matrix.image }}
        # run: python3 dockerfile_generator.py validate ${{ matrix.image }} --lib "cffi"
