name: new

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore: [master]
    paths-ignore:
      - README.md
      # - .github/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: set-matrix
        run: echo ::set-output name=matrix::{\"include\":[$(git diff-tree HEAD HEAD~1 --name-only | awk '{printf "{\"image\":\"%s\"},", $1}')]}

  build:
    needs: get_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.get_matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.image }}
      - run: |
          if [ ! -f ${{ matrix.image }}/Dockerfile ];then echo exit;exit 0; fi
          # if [ -f ${{ matrix.image }}/Dockerfile ]; then echo ${{ matrix.image }} .; else exit 0; fi
          echo no
          IMAGE_NAME=${{ inputs.username }}/${GITHUB_REPOSITORY##*/}
          echo "::set-output name=image::$IMAGE_NAME:${TAG}"
          echo "$IMAGE_NAME:${TAG}"


