name: new

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore: [master]
    paths-ignore:
      - README.md
      # - .github/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: git show |grep diff
      - id: set-matrix
        # run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
        run: echo "::set-output name=matrix::{\"include\":[\"foo\",\"bar\]}"
        # run: echo "::set-output name=matrix::{\"include\":[\"foo\",\"bar\"]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ toJSON(matrix) }}


