name: new

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches-ignore: [master]
    paths-ignore:
      - README.md
      # - .github/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  get_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: set-matrix
        run: echo ::set-output name=matrix::{\"include\":[$(git diff-tree HEAD HEAD~1 --name-only | awk '{printf "{\"tag\":\"%s\"},", $1}')]}

  build:
    needs: get_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.get_matrix.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.tag }}
      - name: ${{ matrix.tag }}
        run: |
          ls -al
          if [ ! -f ${{ matrix.tag }}/Dockerfile ];then echo exit;exit 0; fi
          # IMAGE_NAME=${{ inputs.username }}/${GITHUB_REPOSITORY##*/}
          IMAGE_NAME=xenocider/${GITHUB_REPOSITORY##*/}:${{ matrix.tag }}
          echo "::set-output name=image::$IMAGE_NAME"
          echo "$IMAGE_NAME"
          docker build -t ${IMAGE_NAME}


