# https://docs.github.com/actions/

name: One CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '* * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      url:
        description: target url
        type: string
        required: false
      path:
        default: '/media/upload'
        required: false
        type: string
        description: path (dev)
jobs:

  one:
    runs-on: ubuntu-latest
    container:
      image: xenocider/img:one

    steps:
      - name: One
        run: |
          export URL="${{ github.event.inputs.url }}"
          echo "${{ github.event.inputs.path }}"
          echo "$URL"
          cd /one
          sh run.sh ${{ secrets.TWO }}
